version: '2.3'
services:
  comori-od-static-vue:
    build: 
      context: ../comori-od-static-vue
      args:
        - buildtype=dev_build
        - NODE_OPTIONS="--openssl-legacy-provider"
    container_name: comori-od-static-vue
    ports:
      - "80:80"
    depends_on:
      - comori-od-restapi
    restart: unless-stopped

  comori-od-static-nuxt:
    build: 
      context: ../comori-od-static-nuxt
      args:
        - buildtype=dev_build
        - NODE_OPTIONS="--openssl-legacy-provider"
    container_name: comori-od-static-nuxt
    ports:
      - "3001:3001"
    depends_on:
      - comori-od-restapi
    restart: unless-stopped

  comori-od-es:
    build:
      context: ../comori-od-es
      args:
        - ES_VERSION=${ES_VERSION}
    container_name: comori-od-es
    environment:
      - discovery.type=single-node
      - ES_VERSION=${ES_VERSION}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_config:/usr/share/elasticsearch/config
      - es_logs:/usr/share/elasticsearch/logs
      - ../comori-od-es/hunspell:/usr/share/elasticsearch/config/hunspell
    ports:
      - 9200:9200
    restart: unless-stopped
  
  comori-od-mongo:
    build: ../comori-od-mongo
    container_name: comori-od-mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    command: ['--auth']
    restart: unless-stopped
  
  comori-od-mongoexpress:
    build: ../comori-od-mongoexpress
    container_name: comori-od-mongoexpress
    environment:
      - ME_CONFIG_MONGODB_SERVER=comori-od-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ADMIN_PASSWORD}
    ports:
      - 8081:8081
    depends_on: 
      - comori-od-mongo
    restart: unless-stopped
  
  comori-od-redis:
    build: ../comori-od-redis
    environment: 
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: comori-od-redis
    ports:
      - 6379:6379
    restart: unless-stopped
  
  comori-od-jupyter:
    build: ../comori-od-jupyter
    container_name: comori-od-jupyter
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    volumes:
      - jupyter_data:/home/jupyter
    ports:
      - 8088:8088
    restart: unless-stopped

  comori-od-restapi:
    build: 
      context: ../comori-od-restapi
      args:
        - LOGGING_CFG=logging_cfg_prod.yaml
    container_name: comori-od-restapi
    ports: 
      - 9000:9000
    environment:
      - GEVENT_RESOLVER=ares
      - VIRTUAL_PORT=9000
      - API_TOTP_KEY=${API_TOTP_KEY}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MOBILE_APP_PKEY=${MOBILE_APP_PKEY}
      - MOBILE_APP_PKEY_ECDSA=${MOBILE_APP_PKEY_ECDSA}
    volumes:
      - api_logs:/var/log/comori-od-restapi
    depends_on:
      - comori-od-es
      - comori-od-mongo
      - comori-od-redis
    restart: unless-stopped

  comori-od-bibleapi:
    build: ../comori-od-bibleapi
    container_name: comori-od-bibleapi
    ports:
      - 9002:9002
    restart: unless-stopped

volumes:
  es_data:
    driver: local
  es_config: 
    driver: local
  es_logs:
    driver: local
  mongo_data:
    driver: local
  jupyter_data:
    driver: local
  api_logs:
    driver: local
