version: '3.0'
services:
  comori-od-static-vue:
    environment:
      - VIRTUAL_HOST=test.comori-od.ro,comori-od.ro,www.comori-od.ro,yakis.cloud
      - LETSENCRYPT_HOST=test.comori-od.ro,comori-od.ro,www.comori-od.ro,yakis.cloud
    networks:
      - proxy

  comori-od-es:
    networks:
      - proxy

  comori-od-mongo:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-mongoexpress:
    environment:
      - VIRTUAL_HOST=testmongo.comori-od.ro,mongo.comori-od.ro
      - LETSENCRYPT_HOST=testmongo.comori-od.ro,mongo.comori-od.ro
    networks:
      - proxy

  comori-od-jupyter:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testjupyter.comori-od.ro,jupyter.comori-od.ro
      - LETSENCRYPT_HOST=testjupyter.comori-od.ro,jupyter.comori-od.ro
    networks:
      - proxy

  comori-od-restapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=api.comori-od.ro,testapi.comori-od.ro
      - LETSENCRYPT_HOST=api.comori-od.ro,testapi.comori-od.ro
    networks:
      - proxy

  comori-od-bibleapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testbible-api.comori-od.ro,bible-api.comori-od.ro
      - LETSENCRYPT_HOST=testbible-api.comori-od.ro,bible-api.comori-od.ro
    networks:
      - proxy

  maxmind-update:
    build: ../maxmind-update
    container_name: maxmind-update
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIP_ACCOUNTID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIP_LICENSEKEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - /usr/share/maxmind:/usr/share/GeoIP
    restart: unless-stopped
    networks:
      - proxy

  comori-od-logprocessor:
    build: ../comori-od-logprocessor
    container_name: comori-od-logprocessor
    expose:
      - 9003
    volumes_from:
      - maxmind-update
    volumes:
      - /var/log/comori-od-logprocessor:/var/log/comori-od-logprocessor
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy