version: '3.0'
services:
  comori-od-static-vue:
    build: 
      context: ../comori-od-static-vue
      args:
        - buildtype=prod_build
        - NODE_OPTIONS="--openssl-legacy-provider"
    container_name: comori-od-static-vue
    ports:
      - 1080:80
    depends_on:
      - comori-od-restapi
    restart: unless-stopped

  comori-od-es:
    build: 
      context: ../comori-od-es
      args:
        - ES_VERSION=${ES_VERSION}
    container_name: comori-od-es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ES_VERSION=${ES_VERSION}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/docker/comori-od/comori-od-es/data/:/usr/share/elasticsearch/data
      - /home/docker/comori-od/comori-od-es/config/:/usr/share/elasticsearch/config
      - /home/docker/comori-od/comori-od-es/logs/:/usr/share/elasticsearch/logs
      - /home/docker/comori-od/comori-od-es/hunspell/:/usr/share/elasticsearch/config/hunspell
    expose:
      - "9200"
    restart: unless-stopped

  comori-od-mongo:
    build: ../comori-od-mongo
    container_name: comori-od-mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - /home/docker/comori-od/comori-od-mongo/data/:/data/db
    expose:
      - 27017
    command: ['--auth']
    restart: unless-stopped

  comori-od-mongoexpress:
    build: ../comori-od-mongoexpress
    container_name: comori-od-mongoexpress
    environment:
      - ME_CONFIG_MONGODB_SERVER=comori-od-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ADMIN_PASSWORD}
    ports:
      - 8081:8081
    depends_on: 
      - comori-od-mongo
    restart: unless-stopped

  comori-od-jupyter:
    build: ../comori-od-jupyter
    container_name: comori-od-jupyter
    environment:
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - /home/docker/comori-od/comori-od-jupyter/data:/home/jupyter
    ports:
      - 8088:8088
    restart: unless-stopped

  comori-od-restapi:
    build: 
      context: ../comori-od-restapi
    container_name: comori-od-restapi
    ports: 
      - 9000:9000
    environment:
      - GEVENT_RESOLVER=ares
      - API_TOTP_KEY=${API_TOTP_KEY}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MOBILE_APP_PKEY_ECDSA=${MOBILE_APP_PKEY_ECDSA}
    volumes:
      - /home/docker/comori-od/comori-od-restapi/logs:/var/log/comori-od-restapi
    depends_on:
      - comori-od-es
      - comori-od-mongo
    restart: unless-stopped

  comori-od-bibleapi:
    build: 
      context: ../comori-od-bibleapi
    container_name: comori-od-bibleapi
    expose:
      - 9002
    environment:
      - VIRTUAL_PORT=9002
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy