version: '3.0'
services:
  comori-od-static-vue:
    environment:
      - VIRTUAL_HOST=comori-od.ro,www.comori-od.ro
      - LETSENCRYPT_HOST=comori-od.ro,www.comori-od.ro
    networks:
      - proxy

  comori-od-es:
    networks:
      - proxy

  comori-od-mongo:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-mongoexpress:
    environment:
      - VIRTUAL_HOST=mongo.comori-od.ro
      - LETSENCRYPT_HOST=mongo.comori-od.ro
    networks:
      - proxy

  comori-od-jupyter:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=jupyter.comori-od.ro
      - LETSENCRYPT_HOST=jupyter.comori-od.ro
    networks:
      - proxy

  comori-od-restapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=api.comori-od.ro
      - LETSENCRYPT_HOST=api.comori-od.ro
    networks:
      - proxy

  comori-od-bibleapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=bible-api.comori-od.ro
      - LETSENCRYPT_HOST=bible-api.comori-od.ro
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy