version: '3.0'
services:
  maxmind-update:
    build: ../maxmind-update
    container_name: maxmind-update
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIP_ACCOUNTID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIP_LICENSEKEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - /home/docker/comori-od/maxmind-update/data:/usr/share/GeoIP
    restart: unless-stopped

  comori-od-logprocessor:
    build: ../comori-od-logprocessor
    container_name: comori-od-logprocessor
    expose:
      - 9003
    volumes_from:
      - maxmind-update
    volumes:
      - /home/docker/comori-od/comori-od-logprocessor/logs:/var/log/comori-od-logprocessor
    restart: unless-stopped

  telegraf:
    build:
      context: ../telegraf
      args:
        - CFG=telegraf-nginx.conf
    container_name: telegraf-comori
    volumes:
      - /home/docker/nginx-proxy-manager/data/:/data
    environment:
      - hostname=ubuntu-prod
    restart: unless-stopped
