version: '3.0'
services:
  comori-od-static-vue:
    environment:
      - VIRTUAL_HOST=test.comori-od.ro,comori-od.ro,www.comori-od.ro
      - LETSENCRYPT_HOST=test.comori-od.ro,comori-od.ro,www.comori-od.ro
    networks:
      - proxy

  comori-od-es:
    networks:
      - proxy

  comori-od-mongo:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-mongoexpress:
    environment:
      - VIRTUAL_HOST=testmongo.comori-od.ro,mongo.comori-od.ro
      - LETSENCRYPT_HOST=testmongo.comori-od.ro,mongo.comori-od.ro
    networks:
      - proxy

  comori-od-meet:
    build:  ../comori-od-dummy
    container_name: comori-od-meet
    environment:
      - VIRTUAL_HOST=meet.comori-od.ro
      - LETSENCRYPT_HOST=meet.comori-od.ro
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    expose:
      - 8081
    restart: unless-stopped
    networks:
      - proxy

  comori-od-nextcloud:
    build:  ../comori-od-dummy
    container_name: comori-od-nextcloud
    environment:
      - VIRTUAL_HOST=nextcloud.comori-od.ro
      - LETSENCRYPT_HOST=nextcloud.comori-od.ro
      - VIRTUAL_PORT=8082
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    expose:
      - 8082
    restart: unless-stopped
    networks:
      - proxy

  comori-od-element:
    build:  ../comori-od-dummy
    container_name: comori-od-element
    environment:
      - VIRTUAL_HOST=element.comori-od.ro
      - LETSENCRYPT_HOST=element.comori-od.ro
      - VIRTUAL_PORT=8010
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    expose:
      - 8010
    restart: unless-stopped
    networks:
      - proxy

  comori-od-matrix:
    build:  ../comori-od-dummy
    container_name: comori-od-matrix
    environment:
      - VIRTUAL_HOST=matrix.comori-od.ro
      - LETSENCRYPT_HOST=matrix.comori-od.ro
      - VIRTUAL_PORT=8008
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    expose:
      - 8008
    restart: unless-stopped
    networks:
      - proxy

  comori-od-turn:
    build:  ../comori-od-dummy
    container_name: comori-od-turn
    environment:
      - VIRTUAL_HOST=turn.comori-od.ro
      - LETSENCRYPT_HOST=turn.comori-od.ro
      - VIRTUAL_PORT=3478
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    expose:
      - 3478
    restart: unless-stopped
    networks:
      - proxy

  comori-od-jupyter:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testjupyter.comori-od.ro,jupyter.comori-od.ro
      - LETSENCRYPT_HOST=testjupyter.comori-od.ro,jupyter.comori-od.ro
    networks:
      - proxy

  comori-od-restapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=api.comori-od.ro,testapi.comori-od.ro
      - LETSENCRYPT_HOST=api.comori-od.ro,testapi.comori-od.ro
    networks:
      - proxy

  comori-od-bibleapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testbible-api.comori-od.ro,bible-api.comori-od.ro
      - LETSENCRYPT_HOST=testbible-api.comori-od.ro,bible-api.comori-od.ro
    networks:
      - proxy

  maxmind-update:
    build: ../maxmind-update
    container_name: maxmind-update
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIP_ACCOUNTID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIP_LICENSEKEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - /usr/share/maxmind:/usr/share/GeoIP
    restart: unless-stopped
    networks:
      - proxy

  comori-od-logprocessor:
    build: ../comori-od-logprocessor
    container_name: comori-od-logprocessor
    expose:
      - 9003
    volumes_from:
      - maxmind-update
    volumes:
      - /var/log/comori-od-logprocessor:/var/log/comori-od-logprocessor
    restart: unless-stopped
    networks:
      - proxy

  telegraf:
    build:
      context: ../telegraf
      args:
        - CFG=telegraf-nginx.conf
    container_name: telegraf-comori
    volumes:
      - /home/docker/nginx-proxy-manager/data/:/data
    environment:
      - hostname=ubuntu-prod
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy