version: '3.0'
services:
  comori-od-static-vue:
    ports:
      - 80:80

  comori-od-mongo:
    build:
      args:
        - tag=latest

  comori-od-mongoexpress:
    ports:
      - 8081:8081

  comori-od-jupyter:
    build: 
      args:
        - tag=latest
    ports:
      - 8088:8088

  comori-od-restapi:
    build: 
      args:
        - tag=latest
    ports: 
      - 9000:9000

  comori-od-bibleapi:
    build: 
      args:
        - tag=latest
    ports:
      - 9002:9002
