version: '3.0'
services:
  comori-od-static-vue:
    build: 
      args:
        - buildtype=staging_build
    environment:
      - VIRTUAL_HOST=test.comori-od.ro
    networks:
      - proxy

  comori-od-es:
    networks:
      - proxy

  comori-od-mongo:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-mongoexpress:
    environment:
      - VIRTUAL_HOST=testmongo.comori-od.ro
    networks:
      - proxy

  comori-od-jupyter:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testjupyter.comori-od.ro
      - LETSENCRYPT_HOST=testjupyter.comori-od.ro
    networks:
      - proxy
 
  comori-od-restapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testapi.comori-od.ro
    networks:
      - proxy

  comori-od-bibleapi:
    build: 
      args:
        - tag=latest
    environment:
      - VIRTUAL_HOST=testbible-api.comori-od.ro
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy