version: '3.0'
services:
  comori-od-static-vue:
    environment:
      - VIRTUAL_HOST=test.comori-od.ro,comori-od.ro,www.comori-od.ro
      - LETSENCRYPT_HOST=test.comori-od.ro,comori-od.ro,www.comori-od.ro
    networks:
      - proxy

  comori-od-es:
    networks:
      - proxy

  comori-od-mongo:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-mongoexpress:
    networks:
      - proxy

  comori-od-jupyter:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-restapi:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  comori-od-bibleapi:
    build: 
      args:
        - tag=latest
    networks:
      - proxy

  maxmind-update:
    build: ../maxmind-update
    container_name: maxmind-update
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIP_ACCOUNTID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIP_LICENSEKEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - /home/docker/comori-od/maxmind-update/data:/usr/share/GeoIP
    restart: unless-stopped
    networks:
      - proxy

  comori-od-logprocessor:
    build: ../comori-od-logprocessor
    container_name: comori-od-logprocessor
    expose:
      - 9003
    volumes_from:
      - maxmind-update
    volumes:
      - /home/docker/comori-od/comori-od-logprocessor/logs:/var/log/comori-od-logprocessor
    restart: unless-stopped
    networks:
      - proxy

  telegraf:
    build:
      context: ../telegraf
      args:
        - CFG=telegraf-nginx.conf
    container_name: telegraf-comori
    volumes:
      - /home/docker/nginx-proxy-manager/data/:/data
    environment:
      - hostname=ubuntu-prod
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy