version: '2.3'
services:
  comori-od-static-vue:
    build: 
      context: ../comori-od-static-vue
      args:
        - buildtype=staging_build
        - NODE_OPTIONS="--openssl-legacy-provider"
    container_name: comori-od-static-vue
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=test.comori-od.ro
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    networks:
      - proxy
    depends_on:
      - comori-od-restapi
    restart: unless-stopped

  comori-od-static-nuxt:
    build: 
      context: ../comori-od-static-nuxt
      args:
        - buildtype=staging_build
        - NODE_OPTIONS="--openssl-legacy-provider"
    container_name: comori-od-static-nuxt
    expose:
      - 3001
    environment:
      - VIRTUAL_HOST=testnew.comori-od.ro
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=testnew.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    networks:
      - proxy
    depends_on:
      - comori-od-restapi
    restart: unless-stopped

  comori-od-kibana:
    build: 
      context: ../comori-od-kibana
      args:
        - ES_VERSION=${ES_VERSION}
    container_name: comori-od-kibana
    environment:
      - VIRTUAL_HOST=testkibana.comori-od.ro
      - VIRTUAL_PORT=5601
      - LETSENCRYPT_HOST=testkibana.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
      - KIBANA_USER=${KIBANA_USER}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - kib_config:/usr/share/kibana/config
      - kib_logs:/usr/share/kibana/logs
    expose: 
      - 5601
    networks:
      - proxy
    depends_on:
      - comori-od-es
    restart: unless-stopped

  comori-od-es:
    build: 
      context: ../comori-od-es
      args: 
        - ES_VERSION=${ES_VERSION}
    container_name: comori-od-es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ES_VERSION=${ES_VERSION}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_config:/usr/share/elasticsearch/config
      - es_logs:/usr/share/elasticsearch/logs
      - es_hunspell:/usr/share/elasticsearch/config/hunspell
    expose:
      - "9200"
    networks:
      - proxy
    restart: unless-stopped
  
  comori-od-mongo:
    build: ../comori-od-mongo
    container_name: comori-od-mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    networks:
      - proxy
    command: ['--auth']
    restart: unless-stopped
  
  comori-od-mongoexpress:
    build: ../comori-od-mongoexpress
    container_name: comori-od-mongoexpress
    environment:
      - ME_CONFIG_MONGODB_SERVER=comori-od-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - VIRTUAL_HOST=testmongo.comori-od.ro
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=testmongo.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    expose:
      - 8081
    networks: 
      - proxy
    depends_on: 
      - comori-od-mongo
    restart: unless-stopped

  comori-od-redis:
    build: ../comori-od-redis
    environment: 
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: comori-od-redis
    expose:
      - 6379
    networks:
      - proxy
    restart: unless-stopped
  
  comori-od-jupyter:
    build: ../comori-od-jupyter
    container_name: comori-od-jupyter
    environment:
      - VIRTUAL_HOST=testjupyter.comori-od.ro
      - VIRTUAL_PORT=8088
      - LETSENCRYPT_HOST=testjupyter.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - jupyter_data:/home/jupyter
    expose:
      - 8088
    networks:
      - proxy
    restart: unless-stopped

  comori-od-restapi:
    build: 
      context: ../comori-od-restapi
    container_name: comori-od-restapi
    expose: 
      - 9000
    environment:
      - GEVENT_RESOLVER=ares
      - VIRTUAL_HOST=testapi.comori-od.ro
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=testapi.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
      - API_TOTP_KEY=${API_TOTP_KEY}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MOBILE_APP_PKEY_ECDSA=${MOBILE_APP_PKEY_ECDSA}
    volumes:
      - /var/log/comori-od-restapi:/var/log/comori-od-restapi
    depends_on:
      - comori-od-es
      - comori-od-mongo
    networks:
      - proxy
    restart: unless-stopped

  comori-od-bibleapi:
    build: ../comori-od-bibleapi
    container_name: comori-od-bibleapi
    expose:
      - 9002
    environment:
      - VIRTUAL_HOST=testbible-api.comori-od.ro
      - VIRTUAL_PORT=9002
      - LETSENCRYPT_HOST=testbible-api.comori-od.ro
      - LETSENCRYPT_EMAIL=moscaliuc_ovidiu@yahoo.com
    networks:
      - proxy
    restart: unless-stopped

volumes:
  es_data:
    driver: local
  es_config: 
    driver: local
  es_logs:
    driver: local
  es_hunspell:
    driver: local
  kib_config:
    driver: local
  kib_logs:
    driver: local
  mongo_data:
    driver: local
  jupyter_data:
    driver: local
    
networks:
  proxy:
    name: nginx-proxy