build:
	DOCKER_HOST=ssh://ubuntu-dev docker compose -f docker-compose.yaml -f docker-compose.test.yaml -f docker-compose.nginxtest.yaml --env-file .env-dev build

up:
	DOCKER_HOST=ssh://ubuntu-dev docker compose -f docker-compose.yaml -f docker-compose.test.yaml -f docker-compose.nginxtest.yaml --env-file .env-dev up -d --remove-orphans

remove:
	DOCKER_HOST=ssh://ubuntu-dev docker compose -f docker-compose.yaml -f docker-compose.test.yaml -f docker-compose.nginxtest.yaml --env-file .env-dev down -v

nginx:
	cd ../comori-od-nginx-proxy-test ; DOCKER_HOST=ssh://ubuntu-dev ./deploy-conf.sh

logs:
	DOCKER_HOST=ssh://ubuntu-dev docker compose -f docker-compose.yaml -f docker-compose.test.yaml -f docker-compose.nginxtest.yaml --env-file .env-dev logs --follow --tail 250

hunspell:
	cd ../comori-od-es; DOCKER_HOST=ssh://ubuntu-dev ./deploy-hunspell.sh

metadata: 
	../../tools/loaders/load_metadata.sh --index od --test-host

data:
	../../tools/loaders/load_all.sh --index od --test-host
	../../tools/prepare_diff.sh

init: hunspell metadata data