build:
	DOCKER_HOST=ssh://comori-od-test docker compose -f docker-compose.yaml -f docker-compose.test.yaml --env-file .env-dev build

rebuild:
	DOCKER_HOST=ssh://comori-od-test docker compose -f docker-compose.yaml -f docker-compose.test.yaml --env-file .env-dev build --no-cache

up:
	DOCKER_HOST=ssh://comori-od-test docker compose -f docker-compose.yaml -f docker-compose.test.yaml --env-file .env-dev up -d --remove-orphans

down:
	DOCKER_HOST=ssh://comori-od-test docker compose -f docker-compose.yaml -f docker-compose.test.yaml --env-file .env-dev down

remove:
	DOCKER_HOST=ssh://comori-od-test docker compose -f docker-compose.yaml -f docker-compose.test.yaml --env-file .env-dev down -v

logs:
	DOCKER_HOST=ssh://comori-od-test docker compose -f docker-compose.yaml -f docker-compose.test.yaml --env-file .env-dev logs --follow --tail 250

hunspell:
	cd ../comori-od-es; DOCKER_HOST=ssh://comori-od-test ./deploy-hunspell.sh

es-config:
	cd ../comori-od-es; DOCKER_HOST=ssh://comori-od-test ./deploy-config.sh

metadata: 
	COMORI_OD_API_HOST=https://testapi.comori-od.ro ../../tools/loaders/load_metadata.sh

data:
	DOCKER_HOST=ssh://comori-od-test COMORI_OD_API_HOST=http://comori-od-test:9000 COMORI_OD_ES_HOST=comori-od-test ../../tools/loaders/load_all.sh

bible: 
	COMORI_OD_API_HOST=http://comori-od-test:9000 BIBLE_API=http://localhost:9002 ../../tools/loaders/load_bible.sh	

init: hunspell metadata data