FROM node:latest as build-stage
ARG buildtype
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run $buildtype

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf